### ISSUE TITLE
The redirect() override in the original web page.

### ISSUE THREAD

**Issue by shanewei** [Clouda-team/Cloudajs#11]
It's the method that redirect(queryPath,paramMap,isforce) override in the original web page when i use this method in my project. How to avoid this issue?

**Comment by shanewei** [comment]
This situation can only be seen in the firefox browser, and it is normal in Chrome.

**Comment by tongyao** [comment]
We currently support desktop & mobile webkit browser only. Firefox may encounter some problems.
