### ISSUE TITLE
[Help]App上传到BAE后数据库的配置问题

### ISSUE THREAD

**Issue by mmtdream** [Clouda-team/Cloudajs#14]
各位大神，我按所给的文档做了个Demo，在本地运行都是正常的。然后按照文档里面介绍的，发布到BAE的时候出现了点小问题，还望各位大神指点。问题描述如下：
1）问题出在发布介绍文档（framework-bae.pdf)中的第9步，文档中如下描述：（9）修改sumeru/server/DbCollectionHandler.js
修改该⽂文件第136、137⾏行的username、password，输⼊入分配的username和password
username = "SmrWebApp";//fw.config.get('bae_user');
password = "AppWebSumeru%";//fw.config.get('bae_password');

我严格按照文档中所说的进行修改了，运行失败，socket服务无法启动，提示500内部服务器错误。后来我又尝试着把上面的用户名和密码修改为我们的百度账号，还是不行。需要说明的是：我们已经在BAE的后台创建了一个Mongo的数据库，并且分配了权限给App。各种尝试，始终不行。后来干脆修改为你们上传的一个Demo中的设置，即按如下设置：host = "10.50.147.16";
            port = 43030;
            username = "SmrWebApp";//fw.config.get('bae_user');
            password = "AppWebSumeru%";//fw.config.get('bae_password');
这样设置后，就可以正常运行了。这里的IP和端口都是写死了的，肯定不是最终的解决方案。

2）希望获得的帮助：我想请问一下，这4行代码到底应该怎么设置才能正常启动程序？即host，port，username，password分别应该怎么样设置？这些值从哪里可以获取到？后台是否还需要其他额外的操作或者设置呢？

不胜感激，期待回复！

**Comment by brandnewera** [comment]
请使用最新版的代码库和文档。
https://github.com/brandnewera/sumeru/blob/master/sumeru/server/DbCollectionHandler.js
可以看到这部分已经变为
    host = process.env.BAE_ENV_ADDR_MONGO_IP;
    port = +process.env.BAE_ENV_ADDR_MONGO_PORT;
    username = process.env.BAE_ENV_AK;
    password = process.env.BAE_ENV_SK;

2013/6/7 mmtdream notifications@github.com

**Comment by tongyao** [comment]
```
host = process.env.BAE_ENV_ADDR_MONGO_IP;
port = +process.env.BAE_ENV_ADDR_MONGO_PORT;
username = process.env.BAE_ENV_AK;
password = process.env.BAE_ENV_SK;
```

**Comment by mmtdream** [comment]
这个代码试过了，最开始就是用这个代码，不行才尝试用其他的。我已经更新过了，目前的版本修改日期是5.27.

谢谢。
