### ISSUE TITLE
npm install -g sumeru出错！求高手来解决啊

### ISSUE THREAD

**Issue by pptea** [Clouda-team/Cloudajs#16]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\asus>npm install -g sumeru
npm http GET https://registry.npmjs.org/sumeru
npm http 304 https://registry.npmjs.org/sumeru
npm http GET https://registry.npmjs.org/mkdirp/0.3.3
npm http GET https://registry.npmjs.org/mongodb/1.2.8
npm http GET https://registry.npmjs.org/shelljs/0.0.8
npm http GET https://registry.npmjs.org/uglify-js/2.3.4
npm http GET https://registry.npmjs.org/sockjs/0.3.5
npm http GET https://registry.npmjs.org/redis/0.8.2
npm http 304 https://registry.npmjs.org/mongodb/1.2.8
npm http 304 https://registry.npmjs.org/shelljs/0.0.8
npm http 304 https://registry.npmjs.org/uglify-js/2.3.4
npm WARN package.json uglify-js@2.3.4 No repository field.
npm WARN package.json uglify-js@2.3.4 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm http 304 https://registry.npmjs.org/mkdirp/0.3.3
npm http 304 https://registry.npmjs.org/sockjs/0.3.5
npm http 304 https://registry.npmjs.org/redis/0.8.2
npm http GET https://registry.npmjs.org/node-uuid/1.3.3
npm http GET https://registry.npmjs.org/faye-websocket/0.4.0
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/bson/0.1.5
npm http 304 https://registry.npmjs.org/node-uuid/1.3.3
npm http 304 https://registry.npmjs.org/faye-websocket/0.4.0
npm WARN package.json faye-websocket@0.4.0 No repository field.
npm WARN package.json faye-websocket@0.4.0 'repositories' (plural) Not supported
.
npm WARN package.json Please pick one as the 'repository' field
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/bson/0.1.5
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/amdefine

bson@0.1.5 install C:\Users\asus\AppData\Roaming\npm\nodemodules\sumeru\node
modules\mongodb\node_modules\bson
node install.js || (exit 0)
# 

=                                                                              =

=  Attempting to build bson c++ extension                                      =

=   Windows: no build will be attempted as binaries are prepackaged            =

=   Unix: on failure the package will still install without the C++ extension  =

=                                                                              =
# 

npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/amdefine
C:\Users\asus\AppData\Roaming\npm\sumeru -> C:\Users\asus\AppData\Roaming\npm\no
de_modules\sumeru\sumeru\npm-tools\sumeru
sumeru@0.7.13 C:\Users\asus\AppData\Roaming\npm\node_modules\sumeru
├── mkdirp@0.3.3
├── shelljs@0.0.8
├── redis@0.8.2
├── sockjs@0.3.5 (node-uuid@1.3.3, faye-websocket@0.4.0)
├── mongodb@1.2.8 (bson@0.1.5)
└── uglify-js@2.3.4 (async@0.2.9, optimist@0.3.7, source-map@0.1.22)

C:\Users\asus>s

**Comment by tongyao** [comment]
没有出错，安装已成功
