### ISSUE TITLE
The issue of fade about the method -- doRender(viewName,transition)

### ISSUE THREAD

**Issue by shanewei** [Clouda-team/Cloudajs#18]
why the fade has the same effect of push when i use the doRender(viewName,transition)?

eg:
env.onrender = function(doRender){
        doRender('test', ['fade', 'z-index=-10']);
    };

the code equals to this way.

env.onrender = function(doRender){
        doRender('test', ['push','right ']);
    };

**Comment by jinjinyun** [comment]
The parameter "z-index=-10" is wrong, Please use "doRender('test', ['fade', 'z']); " instead.

**Comment by shanewei** [comment]
Thank you very much!
