### ISSUE TITLE
npm 安装 sumeru 成功后，使用 sumeru init project 提示 sumeru command not found

### ISSUE THREAD

**Issue by siery** [Clouda-team/Cloudajs#19]
使用 sumeru init project 提示 sumeru command not found
我应该如何解决？

**Comment by tongyao** [comment]
安装时需要使用-g命令，如果仍然找不到sumeru，需要去安装路径执行/path/to/node_modules/sumeru/sumeru/npm-tools/sumeru init project 如：/usr/local/lib/node_modules/sumeru/sumeru/npm-tools/sumeru init project

**Comment by siery** [comment]
谢谢，安装使用-g 只能去安装路径执行了
