### ISSUE TITLE
上传到BAE无法运行

### ISSUE THREAD

**Issue by larrykoo711** [Clouda-team/Cloudajs#22]
采用sumeru框架开发了一个应用后，在本地运行都是正常的，安装文档上传到百度BAE后，访问页面，无法显示效果，还报了一个：

``` javascript
Uncaught TypeError: Object #<Object> has no method 'packages' 
```

的错误，请帮忙看看
地址：http://goodaward.duapp.com/index.html#/tdmarquee

**Comment by shanewei** [comment]
你确定是按照上传到BAE的步骤了操作的么？
你看下这一步你修改正确了吗？
（12）修改app/config/sumeru.js文件

将第7行
     location.hostname + ':' + socketPort + '/socket/' : '';
修改成：
     location.hostname + '/socket/' : '';

还有 你可以试试在 app/controller/tdmarquee.js 里加上sumeru.router.setDefault('App.tdmarquee');

然后点击直接试试http://goodaward.duapp.com/

**Comment by shanewei** [comment]
如果你试试http://goodaward.duapp.com/debug.html#/tdmarquee
这样的话 你地址就不会出现你上面的错误了 但是还是访问不了 你可以再看看你代码

**Comment by larrykoo711** [comment]
我确认是安装正确步骤修改了app/config/sumeru.js文件的，css样式都是出来了的，js等资源都有，就是不出现html页面，有一个问题是我运行node runBuild.js后，生成的**bae**里面全是空文件夹，正常么

**Comment by ganxun1** [comment]
正常的，我看了一下你的debug.html中有异常，好像引入的js和css不对，你仔细对照一下 init工程的文件

**Comment by larrykoo711** [comment]
多加了一个js，严格按照init工程的引入来了，重新上传了，还是没有变化呢，debug模式也看不到问题在哪里，麻烦再帮忙看一下

**Comment by larrykoo711** [comment]
问题已经解决，看错了mongodb的dbname的位置，是第12行，大家注意下
