### ISSUE TITLE
访问根域名无法找到controller的问题

### ISSUE THREAD

**Issue by larrykoo711** [Clouda-team/Cloudajs#24]
直接访问  xxx.duapp.com就会出现下面这个错误，加上/index.html#/xxx  就不会有问题，请问这个是哪里配置的呢

``` java
Uncaught Can NOT find a controller [] 
```

**Comment by shanewei** [comment]
在controller下的js里有加上这一行吗？
sumeru.router.setDefault(‘’);

**Comment by larrykoo711** [comment]
多谢，问题解决，这句是设置默认域名访问的，了解
