### ISSUE TITLE
sumeru提供的register方法注册问题

### ISSUE THREAD

**Issue by shanewei** [Clouda-team/Cloudajs#25]
sumeru.auth.register(token, password, info, callback);

我想问下，就是在使用这个函数的时候，该如何来实现回调函数的跳转到注册成功的主界面呢？（也可以给一个大概思路或者详细信息，谢谢！）

在本地测试的时候显示客户端和服务器端都验证通过。

**Comment by shanewei** [comment]
而且注册的用户名和密码等信息在数据库里查看都为空.....

**Comment by tongyao** [comment]
是某些情况下的Bug，我们将会在下一个版本中修复

**Comment by tongyao** [comment]
有同样问题的可更新至最新版
