### ISSUE TITLE
sumeru在windows下的开发如何完成？

### ISSUE THREAD

**Issue by MarsYoung** [Clouda-team/Cloudajs#26]
doc中mongdb和nodejs都是在windows环境下配置的，sumeru却在linux环境下安装，请问在windows下如何使用配置和使用sumeru?

**Comment by tongyao** [comment]
sumeru只依赖与npm和node，所以在windows下只要先安装node，然后使用cmd运行npm命令就可以安装了。其他两个平台应该都是一样的

**Comment by MarsYoung** [comment]
好的，谢谢了，没用过nodejs，本以为npm是在linux运行的。
