### ISSUE TITLE
bae环境上第一次加载应用为什么都有websocket 错误

### ISSUE THREAD

**Issue by haoxiana** [Clouda-team/Cloudajs#28]
Firefox 无法建立到 ws://xxx.sx.duapp.com/socket/591/iqgoqx3a/websocket 服务器的连接。
源文件：http://xxx.duapp.com/bin/sumeru.js 行：5

**Comment by shanewei** [comment]
这应该也是一个还未修复的bug吧，不过这个不影响运行结果吧。

**Comment by tongyao** [comment]
如shane所说，我们将会在下一版本中抑制这个错误报告。但可以放心目前不影响使用
