### ISSUE TITLE
工程部署到BAE无法显示

### ISSUE THREAD

**Issue by speedFeng** [Clouda-team/Cloudajs#32]
工程部署到BAE上面 无法显示
提示错误如下：
Failed to load resource: the server responded with a status of 404 (Not Found) http://myfriday.duapp.com/bin/sumeru.css
Failed to load resource: the server responded with a status of 404 (Not Found) http://myfriday.duapp.com/bin/app.css
Failed to load resource: the server responded with a status of 404 (Not Found) http://myfriday.duapp.com/bin/css/base.css
Failed to load resource: the server responded with a status of 404 (Not Found) http://myfriday.duapp.com/bin/css/index.css
Failed to load resource: the server responded with a status of 404 (Not Found) http://myfriday.duapp.com/bin/jquery.js
Failed to load resource: the server responded with a status of 404 (Not Found) http://myfriday.duapp.com/bin/sumeru.js?cHVzaA=58205
Failed to load resource: the server responded with a status of 404 (Not Found) http://myfriday.duapp.com/bin/app.js
在bin文件夹下的css以及js找不到

在BAE的log上面显示的下面这一个FATAL
FATAL:2013-07-25 11:43:55myfriday.duapp.com
--Error: Cannot find module 'uglify-js'
at Function.Module._resolveFilename (module.js:375:15)
at Function.Module._load (module.js:318:25)
at Module.require (module.js:398:17)
at require (instance0/nodejs/runtime/src/sandbox/modules/module.js:42:15)
at module.exports (instance0/nodejs/myfriday.duapp.com/app/sumeru/build/buildJavascript.js:9:15)
at Object.<anonymous> (instance0/nodejs/myfriday.duapp.com/app/sumeru/build/build.js:45:51)
at Module.wrappedCompile [as _compile](instance0/nodejs/runtime/src/sandbox/modules/module.js:118:25)
at Object.Module._extensions..js (module.js:502:10)
at Module.load (module.js:392:32)
at Function.Module._load (module.js:350:12)

在已经close掉的一个issue里面也发现了这样一个类似的问题
但是我按照答案的方法：更新sumeru 和 工程 
但是都没办法解决 
求解答！

**Comment by shanewei** [comment]
是否你在按照部署到BAE上第（14）步：运行 node runBuild.js时就出线了 
                 Error: Cannot find module 'uglify-js'
如果这时有的话，你先使用命令$ npm install uglify-js，然后在提交上传试试？

**Comment by speedFeng** [comment]
在运行 node runBuild.js的时候  显示如下信息：
Home Dir =/home/speed/baeRoot/appidqu2ctafqh4/1/
BAE MODE
BaseDir :/home/speed/baeRoot/appidqu2ctafqh4/1/
DstDir :/home/speed/baeRoot/appidqu2ctafqh4/1/**bae**
path.existsSync is now called `fs.existsSync`.
/home/speed/baeRoot/appidqu2ctafqh4/1/**bae**/static/hiUpload

并没有出现 Error: Cannot find module 'uglify-js'

在node_modules中也已经有uglify-js文件夹  

这个工程我在本地上可以跑起来  但是放到bae上面就不行了

**Comment by speedFeng** [comment]
应用日志的记录是这样的：
113.111.119.90myfriday.duapp.com-26/Jul/2013:10:26:42 +080040414393451000
appidqu2ctafqh4-------GET /bin/app.js HTTP/1.1http://myfriday.duapp.com/Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36clientId=LLPBwUxEsAz1; mongoMachineId=594074; BAEID=EE0D13FEE023BB6A1149003D02EA51B7:FG=1

显示找不到资源而已.

**Comment by tongyao** [comment]
请查阅
https://github.com/brandnewera/sumeru/blob/master/docs/upload_to_BAE.md

确保每一步都按文档进行。

初步看起来怀疑与app.conf有关，请检查是否与文档中要求的配置一致

**Comment by speedFeng** [comment]
项目部署到bae上  只显示了html内容 但是在bin中添加的css  js 都找不到   只能找到bin下的sumeru.js sumeru.cc  app.js等  ！
还显示这样一个错误：
WebSocket connection to 'ws://myfriday.sx.duapp.com/socket/676/60p6xrce/websocket' failed: Unexpected response code: 200 

请问一下这是什么原因？

**Comment by speedFeng** [comment]
在app下新建一个asset装自己的css js等文件 就可以了 虽然我也不知道为什么放在bin下不行  不过还是解决了！～
