### ISSUE TITLE
sumeru开发的APP，浏览器首次加载较慢，从哪几个方面优化

### ISSUE THREAD

**Issue by jazz1988** [Clouda-team/Cloudajs#33]
sumeru开发的APP，浏览器首次加载较慢，就像卡一下，才出来一样。请问，这可以从哪几个方面优化

**Comment by tongyao** [comment]
可以先等待马上发布的0.8，页面加载速度本身就会有很大的提升。

**Comment by jackton** [comment]
本周能发布么

**Comment by ganxun1** [comment]
你好！现在0.8版本已经发布，请使用npm update -g sumeru命令更新Clouda的版本，使用server渲染功能，页面加载速度本身就会有很大的提升。详细使用说明请参考Clouda官网（cloudajs.org）。
