### ISSUE TITLE
controller跳转后 页面覆盖问题 

### ISSUE THREAD

**Issue by speedFeng** [Clouda-team/Cloudajs#34]
我从 controller A 使用 env.redirect() 跳转到 controller B 后 
按 浏览器的返回按钮  页面会覆盖

检查了一下 
当我从controller A 跳转到 controller B的时候 controller A 的场景并没有消失  而是隐藏了(display:none)  

在controller A 页面未跳转时： 
 <div class="warp" style="width: 100%;">
<section id="view/itworks@@content" class="**viewBlock** **viewBlock** transi _g_push_left_sw"></section>
</div>

跳转到controller B后 
<div class="warp" style="width: 100%;">
<section id="view/itworks@@content" class="**viewBlock** **viewBlock** transi _g_push_left_hd"></section>
<section id="view/hello@@content" class="__viewBlock__ **viewBlock** transi _g_push_left_sw"></section>
</div>

需要在controller B刷新后 才能出现我真正跳转的效果
<div class="warp" style="width: 100%;">
<section id="view/hello@@content" class="**viewBlock** **viewBlock** transi _g_push_left_sw"></section>
</div>

这两个controller都是最简单的例子 controller A 是官方示例itworks  controller B是我自己写的最简单的hello world  所以应该不是我自己代码的问题

看了下env.redirect()中有isforce的参数 我设置了一直还是没有任何效果

我的环境是  ubuntu 12.04 lts 浏览器是 chrome 28.0.1500.71 

求解决..

**Comment by ganxun1** [comment]
在Controller中使用onrender()渲染页面时需要使用转场效果，例如使用doRender("view", ['push','left']);这样就不会出险view覆盖和重叠的问题。具体转场效果请参考 《step4_API_Documentation.md》中transition部分

**Comment by shanewei** [comment]
在Chrome打开则不会覆盖和重叠，但是用firefox打开就会覆盖和重叠。

**Comment by speedFeng** [comment]
@ganxun1  @shanewei   我是在chrome中测试发现的！！  我在controller的转场中使用了push，left的方式  是不出现覆盖的情况！  但是相应的  view在右侧出现了！ 底部出现了滑动跳！body宽度成了浏览器的两倍  ！
  我已经把工程部署到bae上面了！ 域名： myfriday.duapp.com !  
提供测试帐号： 湖北  随州职业技术学院   2012-2013   第二学期 
复现方式 ：当进入第三个页面的时候  底部出现滑动条

**Comment by ganxun1** [comment]
在Clouda官网（http://cloudajs.org）FAQ文档中有详细的解决方法，在CSS中添加下面代码
.wrap{
    overflow-x: hidden;
}

**Comment by tongyao** [comment]
update: 请使用或升级到最新版本即可
