### ISSUE TITLE
Clouda能否与Grunt和bower结合？

### ISSUE THREAD

**Issue by shuai-zh** [Clouda-team/Cloudajs#37]
如果可以，请问有什么需要注意的？

**Comment by yunlongmain** [comment]
理论上可以结合，但没尝试过。如果遇到问题，可以贴出来，一起解决。

**Comment by dnxbf321** [comment]
node下使用grunt打包管理不错哟，我觉得是可以的，因为grunt也可以看作是node_module

**Comment by tongyao** [comment]
多谢，我们会看看是否可以利用grunt帮助我们。bower目前看起来因为缺乏bin的指向，不是特别还是clouda使用
