### ISSUE TITLE
安装错误 直接npm安装或者通过下载后在本地安装都是一样的错误,是有相关的依赖我没安装么?

### ISSUE THREAD

**Issue by t-a-b-l-e** [Clouda-team/Cloudajs#38]
![image](https://f.cloud.github.com/assets/1811657/1021898/dfdfdea8-0d3f-11e3-8cef-8343531a2577.png)

**Comment by shuai-zh** [comment]
估计是网络问题吧，多试两次？

**Comment by neokidd** [comment]
Error: connect ETIMEDOUT. 请检查网络连接。
