### ISSUE TITLE
部署到bae上日志没有什么提示，也运行不起来？

### ISSUE THREAD

**Issue by MarsYoung** [Clouda-team/Cloudajs#39]
![image](https://f.cloud.github.com/assets/1715639/1025604/90b41a64-0e49-11e3-88f2-b139174cbb3c.png)
在本机上win8和ubuntu上我都试过了，还改了端口等，都可以使用。部署之后无法访问，也没有报什么错。不好发现问题。文档中的uploadtobae的介绍也看了好几遍，很多东西与最新的代码对应不上。求更新文档，或者讲解一下如何查看具体部署不成功的原因。谢谢。

**Comment by brandnewera** [comment]
http://cloudajs.org/docs/upload_to_BAE

**Comment by MarsYoung** [comment]
好的，解决了，的确啊，现在的版本什么都不需要改，顶多改下数据库就好了。我这里还发现个问题，就是用svn上传之前最好是先update.
