### ISSUE TITLE
请问有封装了node处理图片保存到mongodb的api吗

### ISSUE THREAD

**Issue by Jaware** [Clouda-team/Cloudajs#43]

**Comment by ganxun1** [comment]
目前在Clouda中没有封装处理图片保存到mongod的API，但是你可以在Controller中使用js算法来处理图片或者直接使用处理图片的JS SDK（例如百度BAE上的图片处理服务），然后将处理后的图片存入mongodb中

**Comment by Jaware** [comment]
俺是新手不大懂，还是没搞明白怎么在Controller里面使用node的api。百度图片服务貌似也是node的，带有require语句什么的，如何在Controller里面使用呢？给个范例呗O(∩_∩)O

**Comment by chenjx1005** [comment]
请问post方式请求第三方数据可以自定义请求header里面的内容吗

在 2013年9月10日上午10:02，zjwphoenix notifications@github.com写道：

**Comment by huang-xin** [comment]
post方式请求第三方数据支持自定义header, 在externalConfig对应的接口中自定义声明即可：

``` js
var options = {
    host : 'some.host.com',
    path : '/' + type,
        headers: {
          //在此自定义header内容
          'Content-Type': ...
    }
}
```

另外，clouda默认的 'Content-Type': 'application/x-www-form-urlencoded'。

**Comment by chenjx1005** [comment]
谢谢~请问可以设置cookie吗？

2013/9/10 einsteinhx notifications@github.com

**Comment by huang-xin** [comment]
可以
