### ISSUE TITLE
clouda是否可以想外部数据提交查询请求？

### ISSUE THREAD

**Issue by anderszhang** [Clouda-team/Cloudajs#44]
看了clouda的几个例子,发现像新闻类的数据抓取应用，clouda有优势，但是向外部站点发起查询请求，显示查询结果的应用，clouda是否可以做？

**Comment by ganxun1** [comment]
在文档中Example部分的SpiderNews就是数据抓取的事例，显示查询结果你可以通过Clouda来完成的而且会很方便。

**Comment by anderszhang** [comment]
我知道clouda可以做数据抓取，但是它的数据抓取是baidu定时去抓外部数据，将数据存到自己的云数据库，但是像一些用户敏感数据不能教给百度。这样如何处理？
