### ISSUE TITLE
Controller里面使用百度图片api

### ISSUE THREAD

**Issue by Jaware** [Clouda-team/Cloudajs#46]
请教一下如何在Controller里面使用百度图片api

**Comment by neokidd** [comment]
百度有多种图片API，你所提到的是哪个呢？请提供链接。

**Comment by Jaware** [comment]
图片旋转以及将图片转为字节的api

**Comment by ganxun1** [comment]
BAE上Image（图片处理）服务是提供node.js的SDK的，提供的功能包括图片变换（Transform）功能、文字水印功能（Annotation） 、二维码功能（QR code） 、验证码(VCode)、图片合成功能（Composition）等。

在百度开发者中心上有详细的说明文档，地址：http://developer.baidu.com/wiki/index.php?title=docs/cplat/rt/node.js/image

这些在Clouda的controller可以直接使用。
