### ISSUE TITLE
【help】sumeru无法工作了

### ISSUE THREAD

**Issue by caomu** [Clouda-team/Cloudajs#47]
我也不知道做了什么操作导致的。目前sumeru命令完全无法使用了
现象，操作系统ubuntu 13.04：
caomu@caomu-Aspire:~$ sumeru start
caomu@caomu-Aspire:~$ sumeru init ./myproject
caomu@caomu-Aspire:~$ 

就是打什么命令下去都是没有反应

**Comment by caomu** [comment]
刚装好的时候，是可以使用的。有没有什么地方可以看日志吗？

**Comment by caomu** [comment]
？？？

**Comment by neokidd** [comment]
为什么先运行“sumeru start”之后才做"sumeru init"呢？日志会在终端显示。请先确保"npm install -g sumeru"已经正确运行过，通常你需要"sudo npm install -g sumeru"来执行。
