### ISSUE TITLE
如何在Sumeru中引用第三方库,如Jquery,Backbone,求指点,多谢!

### ISSUE THREAD

**Issue by t-a-b-l-e** [Clouda-team/Cloudajs#48]
如题!多谢!

**Comment by tongyao** [comment]
http://cloudajs.org/docs/step3_overview

在package.js中不仅可以引入CSS文件，当您需要引入jquery、backbone等第三方的库文件时，也可以在package.js中添加。

**Comment by t-a-b-l-e** [comment]
@tongyao 非常感谢,已经处理好了,当时忙着去弄其它的,直接关闭了问题才回复,抱歉!

**Comment by smallStrongIsMe** [comment]
@biaoqier 关于上面的问题能否给一下你的代码，我尝试了一下，怎么不行
