### ISSUE TITLE
这个框架的websocket是自己写的 还是用开源框架的啊？

### ISSUE THREAD

**Issue by gguava** [Clouda-team/Cloudajs#49]
rt 
还有数据持久化这个框架不管的？ 让用户自己选择？

**Comment by gguava** [comment]
推荐前端用 https://github.com/gimite/web-socket-js 解决ie websocket问题

**Comment by ganxun1** [comment]
框架使用了sockjs，非webkit浏览器暂时我们不会支持 未来会再评估！请继续关注clouda！
