### ISSUE TITLE
很好奇[开发指南]中说的在Sumeru中引用Backbone,引入后怎么做到与Sumeru集成呢?

### ISSUE THREAD

**Issue by t-a-b-l-e** [Clouda-team/Cloudajs#50]
两个库有很多共同点,各有侧重的样子,因为以前用Backbone,所以很好奇[开发指南]中最后说的通过package.js引入Backbone之类的,引入之后呢? 该怎么集成?没有头绪啊,另外,如果在Sumeru中再引用Backbone,会不会有些多余,因为重叠的功能不少!能不能哪位指点一下,谢谢!

**Comment by tongyao** [comment]
可以看看这里：http://cloudajs.org/docs/step3_overview#h3_18
