### ISSUE TITLE
关于site_url的设置问题,怎么样配置域名在本地进行开发测试呢?

### ISSUE THREAD

**Issue by t-a-b-l-e** [Clouda-team/Cloudajs#51]
在/app/server_config/site_url.js中,默认的配置如下:
sumeru.config({
    site_url:"http://localhost:8080/" //with a tailing slash
});
默认情况下我通过localhost进行访问,没有问题,但如果我想改成如下的域名形式
sumeru.config({
    site_url:"http://m.xxx.com" //m.xxx.com 指向了127.0.0.1
});
在/app/config/sumeru.js把httpServerPort的值也改回了80,理论上应该可以直接通过域名就能访问到本地项目啊,可是会出现以下异常:
![image](https://f.cloud.github.com/assets/1811657/1190026/1e014b52-242b-11e3-99b4-598e30941540.png)

感觉这不科学,我需要怎么样才能设置自定义的域名呢?谢谢!

**Comment by tongyao** [comment]
你看原来默认的代码后面注释写着：//with a tailing slash

所以你要配置成http://m.xx.com/ 带着最后的斜杠

**Comment by t-a-b-l-e** [comment]
@tongyao 表示带着最后的斜杠的设置过,还是一样的表现,除了site_url这个 还需要设置其它的么?

**Comment by t-a-b-l-e** [comment]
在/config/sumeru.js加入
sumeru.config({
site_url:"http://m.xxx.com"
});
就可以了!
