### ISSUE TITLE
官网教程 跑不起来

### ISSUE THREAD

**Issue by yinghuihong** [Clouda-team/Cloudajs#53]
在第三步：创建Publish
在 app/publish 文件夹下, 新建文件 chatroom.js:
module.exports = function(fw){
    fw.publish('chatroomModel', 'pub-chatRoom', function(callback){
        var collection = this;
        collection.find({}, {sort:[['time',1]]}, function(err, items){
            callback(items);
         });
    },
...
};
推测问题所在：
新建文件名称chatroom.js与fw.publish中  'pub-chatRoom' 不相同
哪里说得不对，请指教

**Comment by ganxun1** [comment]
你好！你跑不起来指的是什么，有错误信息吗？文件名是可以跟fw.publish中 'pub-chatRoom' 不相同的，这里没有强制的限制。

**Comment by yinghuihong** [comment]
谢谢。发送完消息，没有显示。以为没运行成功。检查了下mongodb数据后，才知已成功添加。
