### ISSUE TITLE
谁能给我示例一下怎么在sumeru中使用JqueryMobile库

### ISSUE THREAD

**Issue by smallStrongIsMe** [Clouda-team/Cloudajs#57]

**Comment by ponych** [comment]
我也是新手，非官方人员。
-  在 app 目录下建立 assets/js 目录，放 js文件
- 编辑 app/package.js 把 js 文件放到里边去，如 

sumeru.packages(
   'config',
   'controller',
   'model',
   'library',
    'assets/js/jquery-2.0.3.js',
    'assets/css/main.css'

);
