### ISSUE TITLE
如何使用第三方node_moules

### ISSUE THREAD

**Issue by three-letter** [Clouda-team/Cloudajs#58]
有上传图片的需求，需要使用formidable，在controller中无法直接require，用package.js好像也不行（参照node_moules的example，不知道是否错误）,需要砸操作，求解

**Comment by ganxun1** [comment]
在clouda中使用第三方的node_modules，先将module放入框架中的node_modules目录下，然后在publish/的文件中使用require引入，在程序中就可以直接使用了。

**Comment by tongyao** [comment]
我们计划在下周会发布一个内置文件上传功能的版本，如果不着急可以等待这个即将到来的版本。
