### ISSUE TITLE
关于< block tpl-id="" >中的block,这个有点纠结!

### ISSUE THREAD

**Issue by t-a-b-l-e** [Clouda-team/Cloudajs#59]
项目中的用jade,版本为0.35.0,纠结之处在于这个block, jade貌似根本不会编译这个block元素成html,但在semeru的controller中使用session.bind的时候,又限制只能使用< block tpl-id="" >,而不能使用< div tpl-id="" >,这很纠结啊,为啥要限制只能使用block而不是自定义元素呢?

**Comment by tongyao** [comment]
Jade的Mixins是否能支持自定义一个block标签？如果不能，暂时可能只有在Jade编译后再通过一个脚本自动把div替换成block了。

我们也不明白Jade为什么只对它可识别的tag做编译，不知道这样下去他们如何兼容Custom Elements呢。

如果我们发现有更好的办法，再第一时间和你讨论。

**Comment by t-a-b-l-e** [comment]
@tongyao 用了一个折中的方案,使用jade的!=处理一下:

!="< block tpl-id='' >"

!="< /block >",
我直接在WebStorm里建了一个Code Templates:
![image](https://f.cloud.github.com/assets/1811657/1303475/fb786030-3158-11e3-9846-262f6a9384a6.png)

**Comment by tongyao** [comment]
Great！ 学习了
