### ISSUE TITLE
some problem!

### ISSUE THREAD

**Issue by lt1946** [Clouda-team/Cloudajs#61]
log:
   getMessage1
   [TypeError: Cannot read property 'modelname' of undefined] 'toLoadEror...'

view:  
   html can't show.

code in js：
   env.onload=function(){
      return [getMessage];
   }

  var getMessage=function(){
      console.log("getMessage1")
      session.siteMassages=env.subscribe("pub-site",function(collections){
          console.log("getMessage2") 
          session.bind("site-container",{data:collections.find()});
      });
   }

**Comment by neokidd** [comment]
Please check how Publish and Model are defined.
