### ISSUE TITLE
後台隨動更新后，前台也跟著刷新了？？？

### ISSUE THREAD

**Issue by lt1946** [Clouda-team/Cloudajs#63]
怎麼讓前台不自動刷新，
比如說遮罩層會自動消失。

**Comment by ganxun1** [comment]
你可以使用hold方法暂停collection实时更新，当需要更新的时候使用releaseHold方法恢复对collection的实时更新，具体使用请参考http://cloudajs.org/docs/step4_API_Documentation#h3_34
