### ISSUE TITLE
关于视图业务代码加载,不能分开加载而不用全部合并到bin/app.js中去吗?

### ISSUE THREAD

**Issue by t-a-b-l-e** [Clouda-team/Cloudajs#64]
sumeru中默认的各视图的controller业务代码全部合并到bin/app.js中去,貌似这不太合

理,如果我有足够多的视图,各controller部分的代码也必然会很多,那么在打开应用页面的

时候我有必要把全部代码一次性加载吗?这样不是造成了初始的时候加载了很多不必要的

代码? 能不能按视图区别,切换到相应的视图才加载这部分代码?还是我什么地方理解错了

呢?求指点!谢谢!

**Comment by ganxun1** [comment]
1.框架所有资源最终都会使用manifest进行缓存,所以不是每次都需要重新加载全部资源.并且框架具备的离线能力最低预期的是可以向用户展现页面并提示网络状态不可用,分次载入在网络不稳定的情况下直接导致无法做任何展现.并且无法预期这种情况出现的时间,从而导至更坏的用户体验.
2.分次加载的情况,用户进入一个新的controller都会等待资源载入,直到用户使用过所有资源的情况下才会有最佳速度体验.而这段时间正好是用户最新接触应用,形成体验印像的时候, 提前预载资源的情况下,用户会在应用启动完成时便得到最佳的速度体验.
综上所述,我们先择的策略为一次载入,随时运行. 欢迎讨论.
