### ISSUE TITLE
一些困惑希望得到解答

### ISSUE THREAD

**Issue by jeremy-dzy** [Clouda-team/Cloudajs#65]
1）关于实时性
    是不是只有在框架下，改动数据库的数据才会实时反映在页面上呢，而直接进mongodb数据库修改数据后，页面就没反应了？例如那个留言板的例程，我进入数据库将之前的数据删除之后，页面不会实时消失原先的数据，要手动刷新页面才会消失。
    本来想试下手动插入数据到数据库中的，但是发现有个 smr_id 字段不知道如何得来的，是不是只能通过框架下的方法插入新数据呢？
2）关于读取本地文件
    好像没有看到帮助文档有关于读取文件的部分，请问下我现在有需求要将本地的文件内容录入到数据库中的话，应该如何实现呢？
3）还是关于数据的录入问题
    如果我想把其它已经持久化的数据迁移过来，有什么办法呢？
4）希望有个快捷的帮助联系方式
    因为在clouda官网没有见到任何联系方式，所以我就厚着脸皮留下自己的邮箱：
    jeremy.dzy@gmail.com
    希望可以得到技术支持，谢谢！

**Comment by ganxun1** [comment]
1.直接修改数据库是不能触发“随动反馈”（数据变化实时反应在页面），在clouda只有通过pubsub机制才能触发“随动反馈”；关于“smr_id”是框架生成并插入数据库的字段，目前只能通过框架来生成
2.clouda没有提供文件读写的内置方法，你可以使用fs来完成这个操作；
3.数据的导入建议使用框架开发一个专门导入数据的程序，这样就可以完成数据迁移，如果是线上数据，可以通过框架中external获取
4.帮助可以加入clouda官方QQ群：315483229
