### ISSUE TITLE
关于Server渲染,总会莫名的不生效,时好时坏,查了很久,没有找到原因!

### ISSUE THREAD

**Issue by t-a-b-l-e** [Clouda-team/Cloudajs#66]
如上,[Server渲染]文档里有写默认是开启的,确实也是这样,但不是一直是这样,用sumeru

开发有一段时间,老是会撞到[Server渲染]没有生效,右键查看源代码只有一点结构代码,不

是全部代码,但页面显示是正常的,也没任何异常抛出,费解啊!

如果要在某个view里插入一段外部js,如:
< script type="text/javascript" src="asset/app.js" ></ script >

我感觉是在[Server渲染]启用了,生效的情况下才,上边的外部js才会加载进来,如果没有生

效的情况下这个外部js是无法加载的,像是被禁用了一样,因为用Chrome[开发者工具]

去"审查元素"的时候上边那一段script标签分明在页面里,只是没有被执行,这个让人压

力很大很痛苦! ︶︹︺

PS:
我的所有页面代码都是放到相应的< block />块中的,不包括在这其中是不会被执行,
sumeru版本0.8.14,  node.js版本0.8.14 (=_= 居然版本号一样)

**Comment by ganxun1** [comment]
server渲染成功运行是有条件的：在使用server渲染时需要注意在controller的onload()中不能包含window，document，Localstorage等浏览器特有的DOM和BOM操作，请查看你的controlelr的onload()是否使用了这些操作，如果使用，可将这些操作在onready()中完成。
