### ISSUE TITLE
onrender事件触发问题？

### ISSUE THREAD

**Issue by zhhigh** [Clouda-team/Cloudajs#68]
已经设置了：server_render:false
设置后，onrender事件还会触法吗？
那些操作会触发onrender事件？我啥工作都没做，居然触发了多次onrender，即发生了多次渲染？？

**Comment by ganxun1** [comment]
server_render是开启server端渲染的开关，这个并不能关闭onrender事件。
onrender()负责完成对视图(View)的渲染和指定转场方式，在下面一下情况下会被执行：
1.当执行初始化controller时，如果在controller中有onrender()，会被执行
2.当server的数据publish到端上时，会触发onrender事件，在onrender中会对数据进行对比，如果数据发生变化，就会刷新相应的视图部分，所以你会看到会多次触发onrender事件
