### ISSUE TITLE
能给个使用jquery mobile 等的例子吗？

### ISSUE THREAD

**Issue by 88baby66** [Clouda-team/Cloudajs#69]
现在的问题是，我想能够打包应用，可是完全没有思路啊。。。。

**Comment by ganxun1** [comment]
在clouda中可以直接使用jquery mobile的，你只需在package.js中包含jquery mobile库就可以直接使用。关于打包应用，你可以根据的实际需要选择一款打包工具，clouda对于打包应用没有特殊的要求。

**Comment by 88baby66** [comment]
非常感谢您的回复，关于打包问题：目前我对clouda的理解是必须要通过index或debug文件启动。那如果我想把index 或debug打包到本地应用中，如何去启动第一个场景呢？

------------------ 原始邮件 ------------------
发件人: "ganxun";notifications@github.com;
发送时间: 2013年10月16日(星期三) 中午11:35
收件人: "brandnewera/sumeru"sumeru@noreply.github.com; 
抄送: "SHARE"843346987@qq.com; 
主题: Re: [sumeru] 能给个使用jquery mobile 等的例子吗？ (#69)

在clouda中可以直接使用jquery mobile的，你只需在package.js中包含jquery mobile库就可以直接使用。关于打包应用，你可以根据的实际需要选择一款打包工具，clouda对于打包应用没有特殊的要求。
