### ISSUE TITLE
BAE发布问题

### ISSUE THREAD

**Issue by Libaier** [Clouda-team/Cloudajs#7]
今天将本地测试通过的Todolist工程提交到BAE上做测试（已经按照https://github.com/brandnewera/sumeru/blob/master/docs/upload_to_BAE.md 这篇文章对工程配置进行更改），但发现打开http://testgc.duapp.com/ 后网页空白。查看网页源代码后发现此页引用的http://testgc.duapp.com/bin/sumeru.css ， http://testgc.duapp.com/bin/sumeru.js ，http://testgc.duapp.com/bin/app.js 都是404 not found。但是非bin文件夹下的文件可以正常找到（如：http://testgc.duapp.com/assets/css/todos.css ）。登录到后台发现bin文件夹以及文件都是存在的。有些不懂，希望路过的大神@tongyao可以帮忙解决下。ps：官方例子中http://sumerutodolist.duapp.com/bin/sumeru.css 是可以找到的。

**Comment by jamesjiang087** [comment]
Please check the app.conf first. Pay attention to this file, you cannot use TAB or other extra symbol which cannot be seen. Just use blank space and Enter. I suggest that you copy it from PDF provided.

If this method has no effect, you would better check if it build correctly. Run runBuild.js before upload, it is very important.

**Comment by ganxun1** [comment]
请npm update -g sumeru升级到最新版本后重新sumeru init再试试！如果还是有问题，麻烦把你的工程包打包发给一下！

**Comment by Libaier** [comment]
这几天在忙其他的所以耽搁了，今天执行了npm update -g sumeru又试着上传了一个helloworld和一个todolist工程，可还是有问题，这是我上传的代码包http://pan.baidu.com/share/link?shareid=672045&uk=3893972583 ，以前没做过相关的东西，小白问题希望能得到帮助~谢谢~@ganxun1 @jamesjiang087

**Comment by ganxun1** [comment]
建议重新使用sumeru init 一个工程，或者使用npm update -g sumeru更新工程，请重新在sumeru/build/ 文件夹下执行node runBuild.js， 我这里init的一个工程按照文档测试没有问题，http://pan.baidu.com/share/link?shareid=517673&uk=4262546430

**Comment by tongyao** [comment]
补充一句，npm update更新了本地安装后，还需要“sumeru update 目录名” 来更新工程才生效
