### ISSUE TITLE
关于clouda的一些问题求教

### ISSUE THREAD

**Issue by zhoushun49** [Clouda-team/Cloudajs#72]
1 clouda框架的性能怎么样？
个人觉得采用nodejs开发web很大的优势在于IO并行，开发简单，灵活性能高。但是clouda给我的感觉是非常沉重，而且限制多不灵活，有学习成本，开发效率感觉肯定比express,meteor等要低，和传统的java（SSH）等比也没有提高多少。那么，它在性能上有优势吗？有没有详细的说明？

2 异常处理相关
之前用node开发时，感觉异常处理不怎么方便。后来引用了淘宝大神的一些中间件好点了。所以这一快一直比较担心，想问下clouda这边有统一的异常处理方式吗？
看官网的教程中的代码，好像异常直接被吃掉了，肯定不妥当：
module.exports = function(fw){
    fw.publish('message', 'pub-message', function(callback){
        var collection = this;
        collection.find({}, {}, function(err, items){
            callback(items);
        });
    });  
}

3 日志相关
同上，有统一便捷的日志输出方式吗 ？

4 web并发，多线程
传统的node是事件轮询，异步回调的机制。但据说meteor等采用了多线程来得到更好的效果。clouda这方面是什么样的方式？

5 水平扩展
如果开发大型分布式应用，clouda支持多核心以及集群吗？

6 适用领域
看官网教程，clouda只支持webkit，是不是意味着clouda完全放弃桌面，只为移动开发？

7 seo能力
官网上说让应用可以被检索，这方面有详细的资料可以介绍一下clouda是怎么做的吗
？

**Comment by tongyao** [comment]
感谢对Clouda的关注，一下子问题比较多，我尽量给出比较详细的回答

1 clouda框架的性能怎么样？
个人觉得采用nodejs开发web很大的优势在于IO并行，开发简单，灵活性能高。但是clouda给我的感觉是非常沉重，而且限制多不灵活，有学习成本，开发效率感觉肯定比express,meteor等要低，和传统的java（SSH）等比也没有提高多少。那么，它在性能上有优势吗？有没有详细的说明？

> 很抱歉Clouda给你感觉非常沉重，这不是我们想看到的。。实际上我们最看重的就是开发灵活和性能高。我们也一直在努力找寻开发灵活和性能高之间的最佳结合点。不过显然还没能让你满意，在这方面我们还有更多的工作要做，也欢迎你指出一些沉重之处，供我们改进。

2 异常处理相关
之前用node开发时，感觉异常处理不怎么方便。后来引用了淘宝大神的一些中间件好点了。所以这一快一直比较担心，想问下clouda这边有统一的异常处理方式吗？
看官网的教程中的代码，好像异常直接被吃掉了，肯定不妥当：
module.exports = function(fw){
fw.publish('message', 'pub-message', function(callback){
var collection = this;
collection.find({}, {}, function(err, items){
callback(items);
});
});
}

> 注意到find的回调中有一个err参数嘛？喏，那就是error对象。 对于异常处理的统一包装，也在我们计划之中，Will let you know.

3 日志相关
同上，有统一便捷的日志输出方式吗 ？

> 还没有。

4 web并发，多线程
传统的node是事件轮询，异步回调的机制。但据说meteor等采用了多线程来得到更好的效果。clouda这方面是什么样的方式？

> Clouda坚持使用着node.js原生的event loop，并且我们相信它可以表现的很好。

5 水平扩展
如果开发大型分布式应用，clouda支持多核心以及集群吗？

> 目前还没有开发多核心能力，集群支持已经有了，近期会把文档发布出来。

6 适用领域
看官网教程，clouda只支持webkit，是不是意味着clouda完全放弃桌面，只为移动开发？

> 是的：）

7 seo能力
官网上说让应用可以被检索，这方面有详细的资料可以介绍一下clouda是怎么做的吗

> 这个够说上一天一夜的了，之前我们在一些线下talk中做过比较详细的介绍，希望哪天有人或者我们自己可以把它整理成文分享给大家。

**Comment by zhoushun49** [comment]
非常感谢楼上朋友详细的回答。
期待clouda的逐步完善，也希望以后文档会越来越完善。
谢谢！

**Comment by haoxins** [comment]
关于seo的部分，有没有相关资料的链接? @tongyao

**Comment by tongyao** [comment]
@coderhaoxin 暂时还没有
