### ISSUE TITLE
在 controller 里 保存一个数据后能 回调吗？

### ISSUE THREAD

**Issue by ponych** [Clouda-team/Cloudajs#73]
即

session.messages.add({
// some data here
});

session.messages.save(callback); //请问支持这个吗？

**Comment by yunlongmain** [comment]
不直接支持传入回调函数。但是有其他方式代替：
1. 在为session.messages赋值的env.subscribe方法内的回调函数中添加
2. 为session.messages添加新的方法onValidation = function(ispass){
            if(ispass){  
            } else {  
            }
        }
