### ISSUE TITLE
在clouda的package.js里头注释是无效的吗？

### ISSUE THREAD

**Issue by einsitang** [Clouda-team/Cloudajs#74]
我在controller/package.js里头想添加多个路由器，但是提示无法找到文件或者目录。
package.js:
sumeru.packages('helloworld.js');
//sumeru.packages('itworks.js');
//sumeru.packages('rrsreader.js');

如果我将注释的两行手动删除掉，再启动项目就可以了，不是因为什么原因吗？好像多行本身也不可以，我记得之前也可以添加多个路由，然后今天突然就不行了，本人新手，求解答！

**Comment by tongyao** [comment]
可以这样 sumeru.packages('helloworld.js', 'itworks.js', 'rssreader.js', .....)

**Comment by tongyao** [comment]
已经fix，最新版本已经支持注释了
