### ISSUE TITLE
sumeru.external.sync疑问

### ISSUE THREAD

**Issue by pigletfly** [Clouda-team/Cloudajs#79]
使用第三方数据,不是采用sumeru.external.get或sumeru.external.post,可以使用sumeru.external.sync手动同步数据吗?

**Comment by tongyao** [comment]
get和post只是区分HTTP METHOD的方法不同，都支持自定义访问URL的逻辑；如果不希望定期更新，可以把interval设置成仅一次；sync方法只是手动触发一次同步，并不包含定义如何同步数据的规则
