### ISSUE TITLE
访问路径问题  /bin/bin/view/itworks.html

### ISSUE THREAD

**Issue by zhhigh** [Clouda-team/Cloudajs#8]
直接下载的demo,运行时没有出现Welcome to sumeru!
看了看打印的日志：
file server accessing /tmp/sumeru-master/app/bin/bin/view/itworks.html
此处有两个bin,明显该路径有问题？是否这个原因造成的？

**Comment by tongyao** [comment]
Please follow the update instruction to get the latest version and give a try.
If problem is still present, please let us know your platform.

OS:
Node Version:
What command you had been using to start the project:

**Comment by zhhigh** [comment]
OS：Linux version 2.6.32-358.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC) ) #1 SMP Fri Feb 22 00:31:26 UTC 2013
Node Version：v0.10.5
sumeru version：0.7.13
在FileServer.js里，有这样一行：filePath = localBase +"/bin"+ filePath，去掉/bin后，重启，/bin/bin/view/itworks.html路径正常，但welcome to sumeru仍然有问题。我看启动信息里有：SockJS v0.3.5 bound to "/socket"，但是这个端口我绑定的是8082，结果发现：GET http://xxx:8082/socket/info 这个一直出错。难道与这个有关？我配置文件里面：var socketPort = (typeof process !== 'undefined' && typeof process.BAE !== 'undefined') ? 80:8082 ;

我用:debug.html#/itworks 和index.html#/itworks都不行。
console.log有这样一个信息：Application Cache Progress event (3 of 6) http://xxxx/bin/view/itworks.html，这个链接进去可以看到welcome to sumeru。
凌乱了，求解。谢谢！另，我没有用bae，用的自己的服务器。

**Comment by ganxun1** [comment]
请使用npm install -g sumeru命令安装sumeru
然后使用sumeru init ./myproject创建一个工程，（注意在实际运行工程之前请先安装mongodb）
在工程文件夹下使用sumeru start 命令启动sumeru
在浏览器中输入： localhost:8080/debug.html#/itworks   访问

看看是否还会出险你说的问题

**Comment by zhhigh** [comment]
不行啊。换了一台机器。linux 32bit的，问题依旧。绝对按照操作步骤来的。在浏览器中输入： localhost:8080/debug.html#/itworks ，什么也没有？有没有人愿意登录来帮忙看看？有的话邮件我，谢谢！

**Comment by speedFeng** [comment]
我也出现了同样的问题。
按照文档的操作
一开始安装sumeru之后，一直无法启动，找了很久发现需要安装mongodb才能启动。（希望文档能写清楚啊！）
启动了之后，遇到了同样的问题：
打开localhost:8080/debug.html#/itworks之后，没有 welcome to sumeru
而此时网页一直在get 8082端口 状态一直是aborted .

**Comment by ganxun1** [comment]
在上面回复中提到了“（注意在实际运行工程之前请先安装mongodb）”，而且在“environment_prepare.md”提到了在运行应用之前“需要安装并启动mongoDB，并保持在后台运行”，我们会在文档中在强调一下，感谢 "speedFeng" 的建议；
我刚刚测试了一下，测试系统是MAC系统，操作如下：
在mongodb/bin 目录下使用 “sudo ./mongod -dbpath ../data/db ”启动mongoDB并保持在后台运行，
然后使用“ sumeru init ./test ”初始化一个工程， 进入工程目录使用 “sumeru  start” 启动，
在浏览器中输入 "http://localhost:8080/debug.html#/itworks" ,在网页中出险"welcome to suemru!"  

请把你的工程文件和操作步骤，运行环境发给我，我测试一下，看看问题出在什么地方！

**Comment by ganxun1** [comment]
sumeru版本：0.7.13

**Comment by zhhigh** [comment]
Node Version：v0.10.5
sumeru version：0.7.13
我的环境，两台机器都这样的环境，都不行。我已经申请了bae，我在bae上试试。悲剧！

**Comment by speedFeng** [comment]
Node version ： v0.10.10
sumeru : 0.7.13
环境  ubuntu 12.04 lts

**Comment by ganxun1** [comment]
你可以把工程包发给我吗？我好看看问问在哪？邮箱：ganxun1@gmail.com

**Comment by speedFeng** [comment]
使用sumeru init webRoot 创建的工程.

**Comment by zhhigh** [comment]
对，使用sumeru init 来创建的工程

发件人： speedFeng
发送时间： 2013-06-06 18:24
收件人： brandnewera/sumeru
抄送： zhhigh
主题： Re: [sumeru] 访问路径问题 /bin/bin/view/itworks.html (#8)
使用sumeru init webRoot 创建的工程.

**Comment by speedFeng** [comment]
工程包已经发你邮箱 请查收

**Comment by zhhigh** [comment]
好，我试试！！
完全按照说明操作的！不知道哪个环节有问题，可能是我人品？

发件人： speedFeng
发送时间： 2013-06-06 18:34
收件人： brandnewera/sumeru
抄送： zhhigh
主题： Re: [sumeru] 访问路径问题 /bin/bin/view/itworks.html (#8)
工程包已经发你邮箱 请查收

**Comment by zhhigh** [comment]
没收到？？

在 2013-06-06 18:34:31，speedFeng notifications@github.com 写道：

工程包已经发你邮箱 请查收

**Comment by speedFeng** [comment]
啊？我发的是ganxun1.

**Comment by zhhigh** [comment]
ganxun1传了一个包给我，可以了。我自己用sumeru init生成的包明显小很多。谢谢ganxun1，很晚了都在帮助解决问题。我关了先。

**Comment by speedFeng** [comment]
麻烦能不能传一个给我 ?

**Comment by ganxun1** [comment]
已经发送给你了，麻烦把你们使用 sumeru inti 的工程发给我一下！

**Comment by ganxun1** [comment]
你好！sumeru版本已更新，请使用 sudo npm update -g sumeru 更新sumeru的版本修复上面的问题

如果是已经init的工程，请修改 app/config/sumeru.js 文件， 将" 80 : 8082;" 改成  "80 : 8081;"  

即可访问itworks demo

**Comment by greenplumm** [comment]
![image](https://f.cloud.github.com/assets/1056982/1731257/2848579a-6300-11e3-80ae-d0e5395abb65.png)
win8 64bit 系统 无法正常浏览itworks demo
出现如上图的问题 ，请教了
