### ISSUE TITLE
onready 得不到调用

### ISSUE THREAD

**Issue by mmlii** [Clouda-team/Cloudajs#80]
sumeru版本：0.8.19

控制器里的 onready 得不到调用，代码如下：
    env.onload = function(){
        console.log("onload")
        return [getNews];
    };

```
env.onready = function(){
    console.log("onready");
};

env.onrender = function(doRender){
    console.log("dorender")
    doRender(view, ['push','left']);
};
```

控制台得到记录到的日志依次为 new, onload, dorender, dorender, destory;

昨天更新版本前是没问题的，更新之后就这样了，这是否是新版本的bug？

**Comment by yunlongmain** [comment]
新版没有这个问题，建议试试官网提供的demo
