### ISSUE TITLE
点击链接时跳转太快

### ISSUE THREAD

**Issue by ktmud** [Clouda-team/Cloudajs#82]
由于 sumeru 拦截了 click 和 touchstart 来管理站内链接的跳转

https://github.com/brandnewera/clouda/blob/master/sumeru/src/controller.js#L542

导致手机轻轻碰到链接就会发生跳转。尤其时当一个 <a> 被写成了一个较大的 block 时。即使是稍微不在垂直方向的滚动窗口，也发送了链接跳转……

需要重新考虑这里对 touchstart 的处理。

FYI：浏览器对链接的默认处理是手指松开后才发送跳转。长按会弹出有关此链接的菜单项……

**Comment by tongyao** [comment]
谢谢，我们跟进一下这个问题

**Comment by huang-xin** [comment]
绑定tap事件就行了, clouda没有事件拦截.

``` js
Library.touch.on(el, "tap", function(e){
     //todos
});
```
