### ISSUE TITLE
请问clouda在windows平台可以使用吗？

### ISSUE THREAD

**Issue by vipbaodao** [Clouda-team/Cloudajs#83]
应如何配置？谢谢

**Comment by ivu4e** [comment]
可以使用的，参考http://blog.csdn.net/segen_jaa/article/details/16118147
不过在安装中可能会遇到很多问题

**Comment by ganxun1** [comment]
这里有详细的步骤：http://forum.cloudajs.org/forum.php?mod=viewthread&tid=9&extra=page%3D1
