### ISSUE TITLE
关于clouda的一些问题（急）！！！

### ISSUE THREAD

**Issue by longyueyi0610** [Clouda-team/Cloudajs#84]
1.我想开发一个轻应用，关于手机分辨率适配这块不是特别明白，希望可以详细讲解。
2.clouda的sumeru.external.get这个方法不知道应该怎么用，在爬取百度新闻的例子中也没有找到，可以给个具体的例子吗？
3.如果轻应用没有账户概念的话，但该轻应用中又有用户关注等功能，需要记录用户关注的东西，应该怎么处理呢？
4.因为轻应用需要从第三方网站get很多图片，缓存怎么处理呢？
5.clouda开发的轻应用必须托管到bae上吗，不托管行吗？
6.为什么我刷新页面很慢呢，我应该用的是最新版本了啊。
希望可以尽快得到大神解答，谢谢！！！

**Comment by sofond** [comment]
个人之见：
#1、分辨率适配问题，用CloudaJS开发的可以当成是Mobile Web，可以做成响应式的，也可以做成640的然后设置page meta
#2、从Api取数据，http://www.cloudajs.org/docs/step3_overview#h3_4 有详细说明，不清楚可以看看以下2个例子：https://github.com/brandnewera/clouda-examples/tree/master/SpiderNews 和 https://github.com/brandnewera/clouda-examples/tree/master/Chatroomv2
#3、不是很明白
#4、图片你访问后就会有缓存了，至少缓存多久要图片服务器那边设置
#5、CloudaJS 开发的不一定要托管在BAE，只是BAE更简单方便而已
#6、页面慢的因素有很多，网络、Api的返回、本机环境、等等，和CloudaJS版本没有关系。
