### ISSUE TITLE
Using auth.baidu.login , How to use the method?

### ISSUE THREAD

**Issue by shanewei** [Clouda-team/Cloudajs#9]
My websit home page has a login button , then I want to click the button to jump the user login pages for auth-baidu-login . how to use the method?

sumeru.auth.baidu.login({
    token: token,
    password: value,
    callback: callback,
    verifyCode: code,
    expires: 1000
});

**Comment by zhanghaihua** [comment]
var accountName = accountNameInput.value;
var pwd = accountPwdInput.value;
var argstr = 'v_code=' +vcodeinput.value;

sumeru.auth.tpa.login(accountName, pwd, argstr, function(response){
    if (response.success) {
        //good
    }
    else {
        var authData = sumeru.auth.getModel().getData();
        if(authData.info && authData.info.v_url){
            //need vcode
        var img = rootBlock.querySelector('#vcodeimg');
        img.src = 'http://vcode.im.baidu.com/cgi-bin/genimg/?' + authData.info.v_url;
        img.onload = function(){
        rootBlock.querySelector('#vcodeLabel').style.display = "block";
        };
        enable_vcode = true;
        }
    }
}

view template sample:

<div id="hiLogin">
    <form action="" id="hiLoginForm">
        <input type="text" name="accountName" placeholder="帐号/邮箱" value="">
        <input type="password" name="accountPwd" placeholder="密码" value="">
        <label id="vcodeLabel" style="display: none;">验证码:<img src="" id="vcodeimg" /><input type="text" name="vcode" id="vcode" maxlength="4"></label>
        <div class="warn-text"></div>
        <div id="statusWrap">
            <label for="status" id="loginStatusLabel">状态：</label>
            <select name="status" id="loginStatus">
                <option value="1">在线</option>
                <option value="2">忙碌</option>
                <option value="3">离开</option>
                <option value="4">隐身</option>
            </select>
        </div>
        
        <div id="loginButtonCenter">
            <input type="submit" value="登录" id="loginButton" class="button primary" />
        </div>
    </form>
</div>

**Comment by shanewei** [comment]
Thank you for you reply my question . I will have a try.

**Comment by tongyao** [comment]
We've removed auth.baidu.login for some internal security reasons in recent versions, but not yet from the API docs.
If you can't get it working right know, you may wait for an update from us with Baidu OAuth, or go to grab an baidu sdk and do it yourself.
